<?php return array(
    'root' => array(
        'name' => 'cakephp/cakephp',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'cakephp/cakephp' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/cakephp-codesniffer' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'reference' => '0f3559af72fd9c2bba7310a7c4496fbb97502352',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/cakephp-codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/debug_kit' => array(
            'pretty_version' => '2.2.9',
            'version' => '2.2.9.0',
            'reference' => '8649a612001fa1caee82d9c432b8223cef221104',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../../Plugin/DebugKit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => 'd20a64ed3c94748397ff5973488761b22f6d3f19',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '1.2.18',
            'version' => '1.2.18.0',
            'reference' => 'fe2466802556d3fe4e4d1d58ffd3ccfd0a19be0b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '1.4.5',
            'version' => '1.4.5.0',
            'reference' => '730b01bc3e867237eaac355e06a36b85dd93a8b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '1.0.9',
            'version' => '1.0.9.0',
            'reference' => '3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'ad4e1e23ae01b483c16f600ff1bebec184588e32',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '3.7.38',
            'version' => '3.7.38.0',
            'reference' => '38709dc22d519a3d1be46849868aa2ddf822bcf6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit-mock-objects' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => '5794e3c5c5ba0fb037b11d8151add2a07fa82875',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit-mock-objects',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'roundcube/plugin-installer' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'shama/baton' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '1.5.6',
            'version' => '1.5.6.0',
            'reference' => '6f3e42d311b882b25b4d409d23a289f4d3b803d5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => 'ef4d7e442ca910c4764bce785146269b30cb5fc4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'reference' => '02c1859112aa779d9ab394ae4f3381911d84052b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
